
const Doctors = [
    {id: 1,
     doctorNumber:"1st",
     age: "0-450",
     wardrobe: "",
     actor: "William Hartnell",
     yearsActive: "1963-66",
     appearances: 134,
     intFact: "filler" ,
     bio: "",

    },
    {id: 2,
     doctorNumber:"2nd",
     age: "450-700",
     wardrobe: "Bowtie, Suspenders & Plaid pants",
     actor: "Patrick Troughton",
     yearsActive: "1966-69",
     appearances: 119,
     intFact: "filler" ,
     bio: ""
    },
    {id: 3,
     doctorNumber:"3rd",
     age: "700-750",
     wardrobe: "",
     actor: "",
     yearsActive: "1970-74",
     appearances: 128,
     intFact: "filler" ,
     bio: ""
    },
    {id: 4,
     doctorNumber:"4th",
     age: "750-813",
     wardrobe: "",
     actor: "",
     yearsActive: "1974-81",
     appearances: 179,
     intFact: "filler" ,
     bio: ""
    },
    {id: 5,
     doctorNumber:"5th",
     age: "813-900",
     wardrobe: "",
     actor: "",
     yearsActive: "1982-84",
     appearances: 69,
     intFact: "filler" ,
     bio: ""
    },
    {id: 6,
     doctorNumber:"6th",
     age: "900-",
     wardrobe: "",
     actor: "",
     yearsActive: "1984-86",
     appearances: 31,
     intFact: "filler" ,
     bio: ""
    },
    {id: 7,
     doctorNumber:"7th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "1987-89",
     appearances: 42,
     intFact: "filler" ,
     bio: ""
    },
    {id: 8,
     doctorNumber:"8th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "1996",
     appearances: "1996 Movie, ",
     intFact: "filler" ,
     bio: ""
    },
    {id: 9,
     doctorNumber:"The War",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: ""
    },
    {id: 10,
     doctorNumber:"9th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: ""
    },
    {id: 11,
     doctorNumber:"10th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: ""
    },
    {id: 12,
     doctorNumber:"11th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: ""
    },
    {id: 13,
     doctorNumber:"12th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: ""
    },
    {id: 14,
     doctorNumber:"13th",
     age: "",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: ""
    },
    {id: 15,
     doctorNumber:"14th",
     age: "",
     wardrobe: "",
     actor: "David Tennant (again)",
     yearsActive: "2023",
     appearances: "60th Anniversary Specials",
     intFact: "filler" ,
     bio: ""
    },
    {id: 16,
     doctorNumber:"15th",
     age: "",
     wardrobe: "",
     actor: "Ncuti Gatwa",
     yearsActive: "2023-present",
     appearances: null,
     intFact: "filler",
     bio: "Gatwa portrays the Doctor in the most unique manner yet",
    },
    {id: 17,
     doctorNumber:"The Fugitive",
     age: "unknown",
     wardrobe: "",
     actor: "",
     yearsActive: "",
     appearances: null,
     intFact: "filler" ,
     bio: "The Fugitive doctor was discovered to be an older iteration of the Timelord"
    }
]


export default Doctors