// import '../Doctors.css';

const Doctors = [
    {id: 1,
     image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxJVCExFLqtEOBurG23tunbb3s70jzUqUITA&s',
     doctorNumber: "1st",
     age: "0-450",
     companions: "Susan Foreman, Barbara Wright, Ian Chesterson, Vicki, Steven Taylor, Katarina, Sara Kingdom, Dodo Chaplet, Polly, Ben Jackson",
     actor: "William Hartnell",
     tenure: "1963-66",
     appearances: 134,
     intFact: "The Doctors first known companion was his own granddaughter, Susan Foreman" ,
     bio: "The 1st Doctor was a complicated figure—sharp, proud, and more than a little mysterious. At first, he didn’t come across as particularly friendly. He could be gruff, impatient, and even a bit selfish, especially when things didn’t go his way. But that rough exterior slowly gave way to something more tender. Over time, you’d catch glimpses of warmth, humor, and a deep sense of responsibility buried under all that sternness. He wasn’t the kind of man to leap into action with a grin or a grand speech. Instead, he observed, questioned, and made careful decisions—often acting more like a watchful elder than a traditional hero. But when he did step in, it mattered. He grew into someone who stood up for what was right, even if he didn’t always show it with a smile. There was a quiet dignity to him, and a sense that, even in his harshest moments, he was trying—slowly but surely—to become someone better.",

    },
    {id: 2,
     image: 'https://ichef.bbci.co.uk/images/ic/480xn/p0217z1z.jpg',
     doctorNumber:"2nd",
     age: "450-700",
     companions: "Polly, Ben Jackson, Jamie McCrimmon, Victoria Waterfield, Zoe Heriot",
     actor: "Patrick Troughton",
     tenure: "1966-69",
     appearances: 119,
     intFact: "The second Doctor was forced by the other Time Lords to regenerate into the third as a punishment" ,
     bio: "The 2nd Doctor initially came across as a bit of a cosmic trickster. At first glance, he seemed scatterbrained and silly, but beneath all the charm and clownish energy was a sharp, calculating mind. He knew exactly what he was doing, and he often let his enemies underestimate him—right up until he turned the tables. He cared deeply for his companions and was never afraid to stand up to cruelty, even if it meant putting himself in danger. There was a quiet steel in him, wrapped in whimsy. That mix of kindness, cleverness, and unpredictability made him easy to love and hard to pin down—exactly the way he liked it."
    },
    {id: 3,
     image: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjpN_SNJSUwokm57HuqMF2qQPggGGEcCg0xMR7WARLB0uJBN2yoQJAzN-JcdHkRtNZU2g9EjL0YllyLSQM1AdiciLTl4xsHzImTN4i1WqORnV0jM_q_u-zRUu-L07KkI7fkTZaqM95XeAk/s1600/Third+Doctor.jpg',
     doctorNumber:"3rd",
     age: "700-750",
     companions: "Liz Shaw, Jo Grant, Sarah Jane Smith",
     actor: "Jon Pertwee",
     tenure: "1970-74",
     appearances: 128,
     intFact: "The Third Doctor was exiled to earth by the Time Lords and was unable to use his TARDIS during that time (though this was really due to budget cuts at the BBC)" ,
     bio: "The 3rd Doctor was all elegance, authority, and action. He carried himself with a kind of refined confidence—more like a secret agent than a wandering alien. Always impeccably dressed in velvet jackets and ruffled shirts, he wasn't shy about being the smartest person in the room and often let people know it. He had little patience for bureaucracy or foolishness and wasn't afraid to speak his mind, especially when someone was in danger. But underneath the style and swagger was a strong, unbending sense of duty. Stranded on Earth for much of his time, he made the best of it by throwing himself into defending the planet—usually alongside UNIT. He loved gadgets, fast cars, and a good intellectual challenge, and while he could be blunt or aloof at times, his loyalty to his friends ran deep. There was real warmth in him, especially in his quieter moments, and he carried himself like a man trying to do good in a world that didn't always make it easy."
    },
    {id: 4,
     image: 'https://ichef.bbci.co.uk/ace/standard/1440/cpsprodpb/d602/live/9f96b7a0-b52b-11ee-beb5-e1400df560f2.jpg',
     doctorNumber:"4th",
     age: "750-813",
     companions: "Sarah Jane Smith, Harry Sullivan, Leela, K9, Romana, Adric, Nyssa of Traken, Teagan Jovanka",
     actor: "Tom Baker",
     tenure: "1974-81",
     appearances: 179,
     intFact: "The 4th Doctor's iconic scarf was actually a mistake, as costume designers who comissioned the scarf gave knitters a mixed bag of yarn and did not specify color or length.",
     bio: "The 4th Doctor was wildly unpredictable—the kind of person who could walk into a room and throw the entire mood off-balance with a grin, a joke, or a sudden flash of intensity. With his impossibly long scarf, wide eyes, and booming voice, he looked and acted like someone from another world—and that was exactly the point. He wasn't trying to fit in; rather he enjoyed being an oddball. He was brilliant, of course, and he knew it. But he rarely showed off in the traditional sense. Instead, he'd leap from nonsense to genius in the same breath, confusing enemies and allies alike. There was a strong moral streak running through him, though it sometimes got buried under layers of eccentricity. He could be warm and funny one moment, then cold and distant the next—especially when facing cruelty or injustice. For all his quirks, there was something fierce about him: a kind of ancient fire behind the eyes that reminded you he wasn't just playing games—he was a force to be reckoned with. "
    },
    {id: 5,
     image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/78/Fifth_Doctor_%28Doctor_Who%29.jpg/250px-Fifth_Doctor_%28Doctor_Who%29.jpg',
     doctorNumber:"5th",
     age: "813-900",
     companions: "Vislor Turlough, Kamelion, Peri Brown",
     actor: "Peter Davidson",
     tenure: "1982-84",
     appearances: 69,
     intFact: "Davidson's daughter, Georgia Davidson, featured in an episode with the tenth Doctor called 'The Doctor's daughter,' where The Doctor's DNA was used in-tandem with human DNA to create a genetic clone, who called herself Jenny. During the filming of this episode, David Tennant and Georgia Davidson hit it off and proceeded to date, and later marry.",
     bio: "The 5th Doctor felt like a breath of fresh air after his more eccentric predecessors. Softer-spoken and more reserved, he brought a quiet thoughtfulness to the role. He looked young, almost too young to carry the weight of centuries, but there was a calm steadiness about him—like someone who had seen too much and chose kindness anyway. He didn't command attention with theatrics; he earned trust through empathy and patience. He was the kind of Doctor who listened first and acted with careful intent. That gentleness made him deeply human, but it also made his struggles feel more raw. He doubted himself at times, carried the consequences of his decisions heavily, and didn't hide the toll that came with being the one who always had to choose. But even in his quiet moments, there was strength. He stood firm when it mattered, especially for the people he cared about. Underneath the cricket whites and polite demeanor was a deeply principled soul—someone who tried to save everyone, even when he knew he couldn't."
    },
    {id: 6,
     image: 'https://static.tvtropes.org/pmwiki/pub/images/sixth_4.jpg',
     doctorNumber:"6th",
     age: "900-953",
     companions: "Melanie Bush",
     actor: "Colin Baker",
     tenure: "1984-86",
     appearances: 31,
     intFact: "filler" ,
     bio: "The 6th Doctor was bold, brash, and completely unapologetic about who he was. He crashed onto the scene with a loud voice, an even louder coat, and a personality that could overwhelm just about anyone in the room. Where other Doctors might have tried to charm their way through a problem, he confronted it head-on, often with biting wit, sharp intellect, and a stubborn streak a mile wide. At first, he could be difficult to warm to. Prickly, arrogant, and not exactly the picture of warmth. But beneath all that bluster was a deep sense of justice and an unwavering belief in doing what was right, even if it meant being unpopular or standing alone. His character softened over time, revealing flashes of vulnerability, compassion, and a fierce loyalty to those he trusted. The Sixth Doctor didn't try to make himself easy to like—but if you stuck with him, you saw a complex, layered figure: fiery, flawed, and absolutely unshakable in the face of darkness."
    },
    {id: 7,
     image: 'https://static.wikitide.net/widwwawiki/thumb/0/01/Seventh_Doctor_S26.jpg/1200px-Seventh_Doctor_S26.jpg',
     doctorNumber:"7th",
     age: "953-1200",
     companions: "Ace",
     actor: "Sylvester McCoy",
     tenure: "1987-89",
     appearances: 42,
     intFact: "filler" ,
     bio: "The 7th Doctor was a mystery wrapped in a charming exterior. At first, he came off as lighthearted and even a little bumbling, but, like every iteration of the Doctor, it was clear there was much more going on beneath the surface. He was calculating, strategic, and sometimes even manipulative, always thinking several steps ahead, often without letting anyone else in on the plan. Something the Doctor would become famous for. This Doctor was a master of misdirection. He used his harmless image to keep people off balance, but when the situation called for it, his tone would shift, his eyes would narrow, and you'd see just how dangerous he could be. He wasn't cruel, but he didn't shy away from difficult choices, and he carried a quiet weight of someone who knew sacrifice. He could be warm and affectionate with his companion, Ace, but kept his distance, emotionally. The Seventh Doctor didn't just fight monsters—he outsmarted them. And sometimes, that made him the most unsettling figure in the room."
    },
    {id: 8,
     image: 'https://i.namu.wiki/i/HzxQu5wEqhwheUxFxH_8y859TL5eWUKztQIpACo6ywUUq4ynUOEyRGPE4HwT6-zDkGVyi0b1tYu-JbVEu9pdZA.webp',
     doctorNumber:"8th",
     age: "1200-",
     companions: "Grace Holloway, Lucie Miller, Charlotte Pollard",
     actor: "Paul McGann",
     tenure: "1996",
     appearances: "1996 Movie, The Night of the Doctor (webisode), The Power of the Doctor",
     intFact: "filler" ,
     bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    },
    {id: 9,
     image: 'https://ichef.bbci.co.uk/images/ic/480xn/p0217syf.jpg',
     doctorNumber:"The War",
     age: "claims to be 'around 800'",
     companions: "none",
     actor: "John Hurt",
     tenure: "2013",
     appearances: "The Day of the Doctor",
     intFact: "The War Doctor was written into Doctor Who as Christopher Eccleston refused to appear in the 50th anniversary of the show. Originally the 9th Doctor would have been the one to have fought in the Time War." ,
     bio: "The Doctor does not consider The War Doctor to be an actual incarnation of 'The Doctor', as he spent this entire incarnation fighting in 'The Time War', a war which lasted about 400 years and effected all of Time and Space"
    },
    {id: 10,
     image: 'https://suzahdi.com/cdn/shop/products/dr-who-jacket-back.jpg?v=1666225798',
     doctorNumber:"9th",
     age: "900",
     companions: "Rose Tyler, Captain Jack Harkness",
     actor: "Christopher Eccelston",
     tenure: "2005",
     appearances: "13",
     intFact: "The 9th Doctor is the only Doctor to have his outgoing Regeneration broadcast before his incoming Regeneration.",
     bio: "The Doctor's 9th incarnation was a man shaped by his loss, but not guided by it. This Doctor didn't hide his scars, rather he carried them wherever he went. There was still an aura of wit and brilliance about him, but they came with an edge of grief. He was a survivor of a war no one else remembered, and it showed. What made him unforgettable was how hard he fought to reclaim his hope. He ran headfirst into danger, reached out to people, and slowly let himself feel again, mostly through his bond with Rose Tyler. With her, he rediscovered laughter, trust, and the belief that he could still make a difference, and he ultimately gave his life to save that of Rose. The Ninth Doctor wasn't the lightest or the easiest, but that's what made him powerful. He chose to be better—not because it was easy, but because he knew what it cost not to."
    },
    {id: 11,
     image: 'https://i.pinimg.com/564x/c2/d6/7a/c2d67a73e0a911d04a2aa28d48be9662.jpg',
     doctorNumber:"10th",
     age: "900-907",
     companions: "Rose Tyler, Captain Jack Harkness, Mickey Smith, Donna Noble, Martha Jones, Wilfred Mott",
     actor: "David Tennant",
     tenure: "2005-2010",
     appearances: 47,
     intFact: "The 10th Doctor was exterminated by a Dalek, but used his own severed arm (long story) as a conduit to regenerate without changing. This means that Tennant has actually played 3 iterations of the Doctor, the most that any actor has portrayed" ,
     bio: "The 10th Doctor is regarded as one of the most 'Human' Doctors. He's a very emotionally complex, energetic and charming individual, often choosing to face dangerous situations with an untimely sense of humor and a large grin on his face. He was one of the only Doctors to become emotionally vulnerable with his companions. Where most incarnations choose to remain more distant, more alien, and ultimately close off the darker parts of who they are, 10 decided to be honest and open with his companions, often leading to Tragedy for one, or both of them, whether it be unrequited love, or life-threatening circumstances. However, this emotional vulnerability also revealed the true darkness the Doctor holds inside, a result of the Trauma he experienced during the Time War. A theme which would continue through future iterations."
    },
    {id: 12,
     image: 'https://theconsultingdetectivesblog.com/wp-content/uploads/2013/12/5180726-low-doctor-who1.jpg' ,
     doctorNumber: "11th",
     age: "907-2000+",
     companions: "Amy Pond, Rory Williams, River Song, Clara Oswald",
     actor: "Matt Smith",
     tenure: "2010-2013",
     appearances: 30,
     intFact: "The 11th Doctor makes his final appearance in the 12th Doctor's first episode, calling his companion Clara in the future to tell him that 12 will still need her, even if he seems different from his 11th incarnation" ,
     bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    },
    {id: 13,
     image: 'https://www.famous-jackets.co.uk/wp-content/uploads/2018/01/12th-Doctor-Who-Coat.jpg',
     doctorNumber:"12th",
     age: "~2000-2100",
     companions: "Clara Oswald, Bill Potts, Nardole",
     actor: "Peter Capaldi",
     tenure: "2013-2017",
     appearances: 40,
     intFact: "Capaldi played the longest-living incarnation of The Doctor, as 12 estimated he spent around 4.5 billion years in the Confession Dial, a prison designed by Time Lords to replicate the prisoners greatest fears, and resurrect them upon their death." ,
     bio: "The 12th Doctor is a darker, more introspective incarnation of the Doctor. Initially a more serious, gruff and blunt Doctor than his predecessors, especially recent incarnations, 12 often asked himself, his best friend Clara, and even at times the audience, if he is a 'good man'. His era explored philosophical questions about identity, duty, and redemption, culminating in a powerful final arc about resisting violence and choosing kindness. His gruff exterior eventually softened to show a very caring, wise, and humorous man, and near the end of his life, he resisted regeneration and almost chose to die, as he believed he had lived too long and seen too many people he loves expire. However, he ultimately decided to continue on as his duty wasn't over"
    },
    {id: 14,
     image: 'https://media.vanityfair.com/photos/5a04889da5d94677ed93cb5c/master/w_1600%2Cc_limit/Doctor%2520Who_S11_Costume%2520Reveal.jpg',
     doctorNumber:"13th",
     age: "2100 - 5000",
     companions: "Rian Sinclair, Graham O'Brien, Yasmin Kahn",
     actor: "Jodie Whittaker",
     tenure: "2018-2022",
     appearances: 31,
     intFact: "The 13th Doctor was the first female iteration of the Doctor to appear onscreen, but discovered that she was not the first female Doctor, as The Fugitive Doctor was revealed to be an incarnation of the Doctor from before she called herself 'The Doctor' and erased her own memories for an unknown reason" ,
     bio: ""
    },
    {id: 15,
     image: 'https://www.crushingkrisis.com/assets/Fourteenth-Doctor-Who-David-Tennant-BBC-Header-Tall-400x613.jpg',
     doctorNumber:"14th",
     age: "5000-unknown",
     companions: "Donna Noble, Rose Noble",
     actor: "David Tennant (again)",
     tenure: "2023",
     appearances: "60th Anniversary Specials",
     intFact: "The 14th Doctor was the first, and only Doctor to not only reappear with the same face, but also to 'Bi-Generate' when killed. A process more like mitosis, where the 15th Doctor split from the 14th, and the two coexist." ,
     bio: "The Doctor subconciously determined that they had unfinished work and regenerated into a former incarnation. Though it technically counts as a new regeneration, the 10th doctors body emerged when the 13th regenerated."
    },
    {id: 16,
     image: 'https://preview.redd.it/what-is-the-best-quote-from-the-fifteenth-doctor-v0-z3c2jums338e1.png?width=446&format=png&auto=webp&s=0bff24f8d4965216087ba065dd3f29c0ca2e8d32',
     doctorNumber:"15th",
     age: "unknown",
     companions: "",
     actor: "Ncuti Gatwa",
     tenure: "2023-present",
     appearances: null,
     intFact: "filler",
     bio: "Gatwa portrays the Doctor in the most unique manner yet, supplying a human-like authenticity unlike any actor before him. Most iterations of the doctor",
    },
    {id: 17,
     image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Fugitive_Doctor_%28Jo_Martin%29.png/250px-Fugitive_Doctor_%28Jo_Martin%29.png',
     doctorNumber:"The Fugitive",
     age: "unknown",
     companions: "unknown",
     actor: "Jo Martin",
     tenure: "2020",
     appearances: "Fugitive of the Judoon, The Story & the Engine",
     intFact: "filler" ,
     bio: "The Fugitive doctor was discovered to be an older iteration of the Timelord"
    }
]


export default Doctors;

